spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/illusionists_service_admin_db
    username: illusionists_user
    password: illusionists_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # create: 시작할 때마다 테이블 삭제 후 재생성 (초기 개발용)
      # update: 변경된 스키마만 반영 (개발용)
      # validate: 엔티티와 테이블이 맞는지 검사만 함 (운영용)
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # 로그에 찍히는 SQL 포맷팅
        show_sql: true   # 실행되는 SQL을 콘솔에 출력 (디버깅용)
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: eWJhY2sKeWJhY2sKeWJhY2sKeWJhY2sKeWJhY2sKOTUxMjIz